config/routes.rb
HeladeraSocialBackend::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'storage_units#index'

  require 'sidekiq/web'
  mount Sidekiq::Web, at: 'sidekiq'
  mount PgHero::Engine, at: 'pghero'

  resources :storage_units, only: [:index, :show, :edit, :update, :create, :new] do
    collection do
      get :favorites
      get :list
      get :map
    end
    member do
      get :pending_donations
      get :product_types
      get :inventory
      post :favorite
      delete :unfavorite
    end
  end

  resources :bar_code do
    collection do
      get :get_product
    end
  end

  resources :donations, only: [:create, :new, :show] do
    collection do
      get :creation_info
    end
    member do
      post :confirm_delivery
    end
  end
  resources :extractions, only: [:create, :new, :show]
  resources :contacts, only: [:create, :new]
  resources :products, only: [:index]

  api_version(module: 'V1', path: { value: 'api/v1' }, defaults: { format: :json }) do
    resources :product_types, only: [:index]
    resources :storage_units, only: [:index]
    resources :donations, only: [:create]
  end
end

app/views/layouts/_footer.html.slim
- if !current_user
  footer.footer-base
    .footer-logo
      .footer-logo-icon
      = image_tag('ic_header_logo.svg')
      = image_tag 'itba.png', class: 'itba-logo'
      h3.h3-base.h3-footer Unite y administrá tu propio comedor social para recibir alimentos
      h2.h2-base.h2-footer info@proyectoalimentar.org
      p.rights © Proyecto Alimentar. Un plato para todos, desperdicio cero.

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'XX-XXXXXXX-X', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.slim
header.header
  = link_to image_tag('ic_header_logo.svg'), storage_units_path
  .header-actions
    .navbar-text
      a.navbar-link href=map_storage_units_path
        = "Mapa"
      a.navbar-link href=storage_units_path
        = "Comedores"
      - if current_user && current_user.manager
        a.navbar-link href=new_donation_path
          = "Ingresar Donación"
        a.navbar-link href=new_extraction_path
          = "Extracción"
        a.navbar-link href=products_path
          = "Productos"
    .navbar-text.navbar-right
      - if current_user
        = link_to('Cerrar Sesión', destroy_user_session_path, method: :delete, class: 'navbar-link')
      - unless current_user
        - if request.path != '/users/sign_in'
          a.navbar-link href=new_session_path(User)  Iniciar Sesión

app/views/layouts/_trello_alert.html.slim
- if Rails.application.secrets.trello_url.present?
  .alert.alert-success
    p
      = "This is a testing site for the new functionalities. If you find any bugs, we ask you to report them in <a target=_blank href=\"#{Rails.application.secrets.trello_url}\">Trello</a>.".html_safe
    p
      = "Este es un sitio de prueba para las nuevas funcionalidades. En caso de encontrar fallas, le pedimos que nos las informe en <a target=_blank href=\"#{Rails.application.secrets.trello_url}\">Trello</a>.".html_safe

app/views/layouts/application.html.slim
doctype html
html
  head
    title Proyecto Alimentar
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = metamagic
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Comedor Social
    javascript:
          var map;
          function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
              center: {lat: -34.6037, lng: -58.3816},
              zoom: 14
            });
          }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" rel="stylesheet" /
    script crossorigin="anonymous" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
    script async="" defer="" src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyA9lViL6yzAuMPIik4vi-3t5_BUJzJsb_I&callback=initMap"
    script src="jquery-3.2.1.min.js"
  body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'